// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package model

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID       int32
	Domain   string
	Name     string
	Email    string
	Password string
}

type Plan struct {
	ID                int32
	Name              string
	Cost              pgtype.Numeric
	BillingPeriodDays pgtype.Int4
}

type Subscription struct {
	ID             int32
	AccountID      pgtype.Int4
	PlanID         pgtype.Int4
	StartDate      pgtype.Timestamptz
	EndDate        pgtype.Timestamptz
	TrialStartDate pgtype.Timestamptz
	TrialEndDate   pgtype.Timestamptz
	Status         pgtype.Int2
	Cost           pgtype.Numeric
}
