// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package model

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Item struct {
	ID          int64
	SectionID   int32
	Name        string
	Type        pgtype.Text
	Duration    pgtype.Int4
	Difficulty  pgtype.Text
	Description pgtype.Text
}

type Module struct {
	ID        int64
	Domain    string
	Category  string
	Purpose   string
	Structure []byte
}

type Section struct {
	ID       int64
	ModuleID int32
	Name     string
	Position pgtype.Int4
}

type Variation struct {
	ID          int64
	ModuleID    int32
	Name        string
	Description pgtype.Text
}

type VariationsItem struct {
	ID          int64
	VariationID int32
	ItemID      int32
	Position    pgtype.Int4
}

type VariationsSection struct {
	ID          int64
	VariationID int32
	SectionID   int32
	Position    pgtype.Int4
}
