// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package model

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CoachingPage struct {
	CoachingID int32
	PageID     int32
}

type Content struct {
	ID            int64
	PageID        int32
	Html          pgtype.Text
	Css           pgtype.Text
	JsonStructure []byte
	PublisedAt    pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type MeetingPage struct {
	MeetingID int32
	PageID    int32
}

type Page struct {
	ID                 int64
	Kind               int32
	Title              pgtype.Text
	Slug               pgtype.Text
	WorkingContentID   int32
	PublishedContentID pgtype.Int4
}
