// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: modules.sql

package model

import (
	"context"
)

const getModule = `-- name: GetModule :one
SELECT id, domain, category, purpose, structure FROM modules
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetModule(ctx context.Context, id int64) (Module, error) {
	row := q.db.QueryRow(ctx, getModule, id)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Category,
		&i.Purpose,
		&i.Structure,
	)
	return i, err
}
